#!/bin/bash -eu

check() {
    local regen=0
    for deb in *.deb; do
        if [[ Packages -ot $deb ]]; then
            regen=1
            break
        fi
    done
    if (( ! $regen )); then
        exit
    fi
}

generate_index() {
    #echo 'update-index: Regenerating local index...' >&2
    apt-ftparchive packages . > Packages
    apt-ftparchive release . > Release
}

gh_latest_version() {
    base=$1
    wget --spider -qS $base 2>&1|sed -r 's|  Location: .*/v?([^/]+)$|\1|p;d'
}

ghurl() {
    repos=$1
    fmt=$2

    base="https://github.com/${repos}/releases/latest/download"
    ver=$(gh_latest_version $base)
    printf "${base}/${fmt}\n" $ver
}

url_from_redirect() {
    wget --spider -qS "$1" 2>&1|sed -n 's/ *location: *//p'
}

bat() {
    ghurl sharkdp/bat 'bat_%s_amd64.deb'
}

delta() {
    ghurl dandavison/delta 'git-delta_%s_amd64.deb'
}

zoom() {
    echo 'https://zoom.us/client/latest/zoom_amd64.deb'
}

discord() {
    url_from_redirect 'https://discord.com/api/download?platform=linux&format=deb'
}

pkgs=(bat zoom delta discord)

for pkg in ${pkgs[@]}; do
    wget -qN "$($pkg)" &
done

wait

check
generate_index
