#!/bin/bash -eu

log() {
    if (( opts[verbose] )); then
        msg "$@"
    fi
}

msg() {
    echo "$progname: $@" >&2
}

check() {
    log 'Check the need to genrerate indexes'
    for deb in *.deb; do
        if [[ Packages -ot $deb ]]; then
            log 'Check done, will generate'
            return
        fi
    done
    log 'Check done. No need to genrerate, exiting'
    exit
}

generate_index() {
    log 'Generating local indexes'
    (( opts[simulate] )) && return
    apt-ftparchive packages . > Packages
    apt-ftparchive release . > Release
    log 'Generating done'
}

gh_latest_version() {
    local -r base="$1"

    wget --spider -qS $base 2>&1|sed -r 's|  Location: .*/v?([^/]+)$|\1|p;d'
}

ghurl() {
    local -r repos="$1" fmt="$2"

    local -r base="https://github.com/${repos}/releases/latest/download"
    local -r ver=$(gh_latest_version ${base})
    printf "${base}/${fmt}\n" $ver
}

bat() {
    ghurl sharkdp/bat 'bat_%s_amd64.deb'
}

delta() {
    ghurl dandavison/delta 'git-delta_%s_amd64.deb'
}

zoom() {
    echo 'https://zoom.us/client/latest/zoom_amd64.deb'
}

discord() {
    echo 'https://discord.com/api/download?platform=linux&format=deb'
}

parseopts() {
    local -A lopts=()
    for arg in "$@"; do
        if [[ ${arg} =~ ^-- ]]; then
            lopts[${arg/--/}]=1
        fi
    done
    declare -p lopts | sed 's/.*lopts=//'
}

update_index() {
    local -ra pkgs=(bat zoom delta discord)
    local wget=wget
    eval opts=$(parseopts "$@")
    (( opts[simulate] )) && wget='echo wget'

    log 'wget(1)ing all pacakges with timestamp checking'
    for pkg in ${pkgs[@]}; do
        $wget --content-disposition -qN "$($pkg)" &
    done

    wait

    if (( opts[force] )); then
        msg 'Forcing to generate files without checking'
    else
        check # may exit
    fi
    generate_index
}

declare progname
declare -A opts
main() {
    local -r me="$(readlink -f $0)"
    progname=$(basename "$me")
    cd $(dirname "$me")
    update_index "$@"
}

main "$@"
